name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-versions:
    name: Validate versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate versions
        run: |
          TOML_VERSION=$(grep 'appVersion =' gradle/libs.versions.toml | cut -d= -f2 | cut -d\" -f2)
          PROPERTIES_VERSION=$(grep 'version=' pico-automator-cli/src/main/resources/version.properties | cut -d= -f2)

          if [ "$TOML_VERSION" != "$PROPERTIES_VERSION" ]; then
            echo "Versions in 'libs.versions.toml' don't match with 'version.properties'"
            exit 1
          fi

  check-code-style:
    name: 'Check code style'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download ktlint binary
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.48.2/ktlint
          chmod +x ktlint

      - name: Run ktlint
        run: ./ktlint --editorconfig=".editorconfig"

  run-tests:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Run tests
        run: ./gradlew test

      - name: Upload coverage.csv file
        uses: actions/upload-artifact@v3
        with:
          name: coverage.csv
          path: pico-automator/build/reports/coverage/coverage.csv

  build-jar:
    name: 'Build jar'
    needs: [ check-code-style, run-tests, validate-versions ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup version variable
        run: |
          echo "VERSION=$(grep 'version=' pico-automator-cli/src/main/resources/version.properties | cut -d= -f2)" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build jar
        run: ./gradlew shadowJar

      - name: Rename jar file
        run: |
          mv pico-automator-cli/build/libs/pico-automator-cli-${{env.VERSION}}-all.jar pico-automator.jar

      - name: Store jar file
        uses: actions/upload-artifact@v3
        with:
          name: pico-automator.jar
          path: pico-automator.jar

  create-coverage-badge:
    needs: [ build-jar ]
    name: 'Create coverage badge'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get coverage.csv
        uses: actions/download-artifact@v3
        with:
          name: coverage.csv
          path: artifacts

      - name: Create JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.8.1
        with:
          jacoco-csv-file: artifacts/coverage.csv
          badges-directory: .github/badges
          generate-coverage-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{steps.jacoco.outputs.coverage}}"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Commit coverage badge'
          add: '*.svg'
