name: Publish to Github and Google Play

on:
  push:
    branches: master
    tags:
      - '*.*.*'

jobs:
  publish-github-release:
    name: Publish Github release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build jar
        run: ./gradlew shadowJar

      - name: Setup version variable
        run: |
          echo "VERSION=$(grep 'version=' pico-automator-cli/src/main/resources/version.properties | cut -d= -f2)" >> $GITHUB_ENV

      - name: Rename jar file
        run: |
          mv pico-automator-cli/build/libs/pico-automator-cli-${{env.VERSION}}-all.jar pico-automator.jar

      - name: Store jar file
        uses: actions/upload-artifact@v4
        with:
          name: pico-automator.jar
          path: pico-automator.jar

      - name: Publish Github Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: true
          files: ./pico-automator.jar